apiVersion: v1
kind: Service
metadata:
  name:  ubs-app-service
  namespace: ubs-dev
spec:
  type: NodePort
  selector:
    app: ubs-app
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
